---
title: "Introduction to R Maps"
author: "Manish Gyawali"
date: 2021-01-27
categories: ["R"]
tags: ["R Markdown", "plot", "regression","maps"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, message = FALSE, warning = FALSE, 
  echo = FALSE, comment = NA)
```

```{r}
library(dash)
library(dashHtmlComponents)
library(dashCoreComponents)

app = Dash$new()

df = gapminder::gapminder

continents = unique(df$continent); years = unique(df$year)

app$layout(
  htmlDiv(
    list(
      dccGraph(id = "graph-with-slider"),
      dccSlider(
        id = "year-slider",
        min = 0,
        max = length(years) - 1, 
        marks = years,
        value = 0
      )
    )
  )
)

app$callback(
  
  output = list(id = "graph-with-slider", property = "figure"),
  params = list(input(id = "year-slider", property = "value")),
  
  function(selected_year_index){
    
    selectedYear = which(df$year == years[selected_year_index + 1])
    
    traces = lapply(continents,
                    function(cont){
                      selectedContinent = which(df$continent == cont)
                      df_sub = df[intersect(selectedYear,selectedContinent),]
                      
                      with(
                        df_sub,
                        list(
                          x = gdpPercap,
                          y = lifeExp,
                          opacity = 0.5,
                          text = country,
                          mode = "markers",
                          marker = list(
                            size = 15, 
                            line = list(width = 0.5, color = "white")
                          ),
                          name = cont
                        )
                      )
                    }
                    
                )
    
    list(
      data = traces,
      layout = list(
        xaxis = list(type = "log", title = "GDP Per Capita"),
        yaxis = list(title = "Life Expectancy", range = c(20,90)),
        margin = list(l = 40, b = 40, t = 10, r = 10),
        legend = list(x = 0, y = 1),
        hovermode = "closest"
      )
    )
    
  }
  
)

app$run_server()
```








